server:
  port: 8888
  max-http-header-size: 102400
  tomcat:
    max-http-form-post-size: 10MB
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  thymeleaf:
    suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ch.pojo